spring:
  application:
    name: todo-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/tododb
    username: lahiru
    password: lahiru

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
